[project]
name = "book-alchemy"
version = "0.1.0"
description = "A Flask web app for managing a personal digital library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-sqlalchemy>=3.1.1",
    "jinja2>=3.1.6",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "mypy>=2.3.0",
]
